# . travis.yml
language: go
sudo: false
go:
  - 1.13
  - master
# before_install:
#  - go get github.com/mattn/goveralls
script:
  - ./.travis.gofmt.sh
  # - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v -race $(go list ./... | grep -v vendor) 
  # $(go list ./... | grep -v vendor) generates list of testable packages without vendor directories