# . travis.yml
language: go

sudo: false

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - tip

script: 
  - ./.travis.gofmt.sh
  - go tests -v -race $(go list ./mathPackage/... | grep -v vendor)