# . travis.yml
language: go
sudo: false
go:
  - 1.13
  - master
before_install:
#  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  # - ./.travis.gofmt.sh
  - go test -v -race $(go list ./... | grep -v vendor) -covermode=atomic -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
  # - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
  # $(go list ./... | grep -v vendor) generates list of testable packages without vendor directories